name: Python CI and testing

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
    steps:
    - name: Copy the code to test
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7.1
    - name: install dependencies
      run: python -m pip install --update pip && install pytest
    - name: Test code with pytest
      run: pytest
